# Generated by Django 3.1.5 on 2021-03-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_auto_20210322_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycalendar',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
