# Generated by Django 3.1.5 on 2021-03-23 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0007_auto_20210322_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='startime',
            new_name='starttime',
        ),
    ]
