# Generated by Django 3.1.5 on 2021-03-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0009_auto_20210322_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='startime',
            new_name='starttime',
        ),
        migrations.AddField(
            model_name='request',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='conflict',
            field=models.ManyToManyField(blank=True, null=True, to='backend_app.Event'),
        ),
    ]
