# Generated by Django 3.1.5 on 2021-03-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0010_auto_20210322_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='endtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='requesttime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='starttime',
            field=models.DateTimeField(),
        ),
    ]
