# Generated by Django 3.1.5 on 2021-03-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0011_auto_20210322_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='endtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='starttime',
            field=models.DateTimeField(),
        ),
    ]
