# Generated by Django 3.1.5 on 2021-03-26 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0012_auto_20210322_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='group',
        ),
        migrations.AddField(
            model_name='request',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.group'),
        ),
    ]
