# Generated by Django 3.1.5 on 2021-04-08 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0013_auto_20210325_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='manager',
        ),
    ]
